# Generated by Django 3.0.1 on 2020-01-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
