# Generated by Django 3.0.1 on 2020-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0002_code_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='handle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='handle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
